apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podiumd-adapter.fullname" . }}
  labels:
    {{- include "podiumd-adapter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "podiumd-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "podiumd-adapter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "podiumd-adapter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- else }}
          imagePullPolicy: Always
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          envFrom:
            - configMapRef:
                name: podiumd-adapter-config
            - secretRef:
                name: podiumd-adapter-secrets
          env:
            {{- if and .Values.extraTrustedCA.enabled .Values.extraTrustedCA.setSslCertFile }}
            - name: SSL_CERT_FILE
              value: {{ .Values.extraTrustedCA.mountPath }}
            {{- end }}
          volumeMounts:
            {{- if .Values.extraTrustedCA.enabled }}
            - name: extra-ca
              mountPath: {{ .Values.extraTrustedCA.mountPath }}
              subPath: {{ .Values.extraTrustedCA.certFilename }}
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.extraTrustedCA.enabled }}
      volumes:
        - name: extra-ca
          configMap:
            name: {{ .Values.extraTrustedCA.configMapName }}
      {{- end }}
