{{- if and (.Values.ingress.host) (.Values.ingress.secretName) -}}
{{- $fullName := include "podiumd-adapter.fullname" . -}}
{{- $releaseName := .Release.Name }}
{{- $svcPort := .Values.service.port -}}
{{- $host := .Values.ingress.host -}}
{{- $secret := .Values.ingress.secretName -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "podiumd-adapter.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ $secret }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $releaseName }}
                port:
                  number: 8080
{{- end }}
