image:
  pullPolicy: Always
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: www.my-website.nl
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: podiumd-adapter
          servicePort: 8080
  tls:
    - hosts:
        - www.my-website.nl
      secretName: wildcard-kiss-tls
cronjobs: []
